 Create table Category(
 id IDENTITY,
 name VARCHAR(50),
 description VARCHAR(255),
 img_url VARCHAR(50),
 is_active BOOLEAN,
 
 CONSTRAINT pk_category_id PRIMARY KEY (id)
 
 
 );
 
create table user_detail(uid Identity,FNAME VARCHAR(50),LNAME VARCHAR(50),ROLE VARCHAR(50),ENABLE BOOLEAN, 
PASSWORD VARCHAR(60), 
EMAIL VARCHAR(255),CONTACT VARCHAR(15), 
CONSTRAINT pk_uid PRIMARY KEY (uid) );

 insert into user_detail(FNAME,LNAME,ROLE,ENABLE,PASSWORD,EMAIL,CONTACT) values('Pooja','Pal','ADMIN','true','poojaknp','pooja90@yahoo.com',9594260496);
  insert into user_detail(FNAME,LNAME,ROLE,ENABLE,PASSWORD,EMAIL,CONTACT) values('Shreya','yadav','user','true','shreya','shreya@gmail.com',9594046863);
   insert into user_detail(FNAME,LNAME,ROLE,ENABLE,PASSWORD,EMAIL,CONTACT) values('Shailesh','Shyam','user','true','shaily','shail@gmail.com',8689858936);
   insert into user_detail(FNAME,LNAME,ROLE,ENABLE,PASSWORD,EMAIL,CONTACT) values('Aashish','kumar','ADMIN','true','ashu','ashish@yahoo.com',7738216638);
   
   
   
   
   CREATE TABLE PRODUCT(PID IDENTITY,CODE VARCHAR(50),NAME VARCHAR(50),BRAND VARCHAR(50),DESCRIPTION VARCHAR(50),
   UNIT_PRICE DECIMAL(10,2),IS_ACTIVE BOOLEAN,CATEGORY_ID INT,
   SUPPLIER_ID INT,PURCHASES INT DEFAULT 0,PRO_VIEW INT DEFAULT 0,
   CONSTRAINT pk_pid PRIMARY KEY (PID),
   CONSTRAINT FK_ID FOREIGN KEY (CATEGORY_ID) REFERENCES Category(id),
     CONSTRAINT FK_uID FOREIGN KEY (SUPPLIER_ID) REFERENCES user_detail(uid));
   
   
   INSERT INTO PRODUCT(CODE,NAME,BRAND,DESCRIPTION,UNIT_PRICE,IS_ACTIVE,CATEGORY_ID,SUPPLIER_ID,PURCHASES,PRO_VIEW)
   				VALUES('P001','TRENDY','ADIDAS','BRANDED COTTON  CLOTHES',500,'TRUE',1,2,0,0);
   				
   INSERT INTO PRODUCT(CODE,NAME,BRAND,DESCRIPTION,UNIT_PRICE,IS_ACTIVE,CATEGORY_ID,SUPPLIER_ID,PURCHASES,PRO_VIEW)
   				VALUES('P002','TRADITIONAL','BOGNER',' COTTON SILK  CLOTHES',1200,'TRUE',1,2,5,10);
   INSERT INTO PRODUCT(CODE,NAME,BRAND,DESCRIPTION,UNIT_PRICE,IS_ACTIVE,CATEGORY_ID,SUPPLIER_ID,PURCHASES,PRO_VIEW)
   			VALUES('P011','TRENDY','BRIONI','BRANDED COTTON  CLOTHES',1500,'TRUE',1,2,3,20);
   
   
   
   
   
   
   
   
   
   
   